string COMPACT_TRANSIT=COMPACT_TRANSIT
string LOADED_TRANSIT=LOADED_TRANSIT
string SHELF_APPROACH=SHELF_APPROACH
string DELIVERY_APPROACH=DELIVERY_APPROACH
string MANIPULATION_EXTENDED=MANIPULATION_EXTENDED
string profile
---
bool applied
string active_profile
string detail
